import Head from "next/head";
import { GrGithub, GrGraphQl } from "react-icons/gr";
import Matrix from "@/dataStructures/Matrix";
import { cMatrix } from "@/components/Board";
import {
  SiTypescript,
  SiNextdotjs,
  SiCss3,
  SiHtml5,
  SiPostgresql,
  SiReact,
} from "react-icons/si";
import { DiGithubFull } from "react-icons/di";
import { GrNode } from "react-icons/gr";
import Me from "@/components/Me";
import TextEditor from "@/components/TextEditor";
import Link from "next/link";
import Grid from "@/components/Grid";
import Board from "@/components/Board";
import { useEffect, useState } from "react";
export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setLoading(false);
    if (window.innerWidth > 390 && window.innerWidth < 450) {
      const board = document.getElementById("board");
      const p = document.getElementById("proj-p");
      if (p) {
        document.getElementById("git-btn")!.style.marginLeft = "-100px";
        p.style.width = "160px";
        p.style.marginLeft = "10px";
      }
      if (!!board) {
        document.getElementById("chess-info")!.style.right = "10px";
        board.style.marginRight = "275px";
      }
    }
    if (window.innerWidth > 420 && window.innerWidth < 440) {
      const board = document.getElementById("board");
      const p = document.getElementById("proj-p");
      if (p) {
        document.getElementById("git-btn")!.style.marginLeft = "-100px";
        p.style.width = "160px";
        p.style.marginLeft = "10px";
      }
      if (!!board) {
        document.getElementById("chess-info")!.style.right = "0px";
        board.style.marginRight = "275px";
      }
    }
  }, [loading]);
  return (
    <>
      <Head>
        <title>Jorden Rodriguez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Me />
      <div className="logo-container">
        <span className="span-bar1"></span>
        <div className="logos">
          <SiTypescript style={{ color: "#007ACC" }} />
          <GrGraphQl style={{ color: "#E10098" }} />
          <SiReact style={{ color: "#61DBFB" }} />
          <GrNode style={{ color: "lightgreen" }} />
          <SiNextdotjs style={{ color: "white" }} />
          <SiCss3 style={{ color: "#2965f1" }} />
          <SiHtml5 style={{ color: "#f06529" }} />
          <SiPostgresql style={{ color: " #0064a5" }} />
        </div>
        <span className="span-bar2"></span>
      </div>
      <p style={{ color: "grey", fontWeight: "200", marginTop: "45px" }}>
        recent projects
      </p>
      <div className="projects-container">
        <TextEditor />
        <div className="projects-info">
          <h1>Projects</h1>
          <hr style={{ border: "solid 1px rgb(18, 18, 18)" }}></hr>
          <p id="proj-p">
            These are just two of my recent projects.
            <br></br>
            All my projects all packed with all sorts of tech from
            <br></br>
            Typescript to C++ theres something for everyone!
            <br></br>
            feel free to browse the rest on GitHub!
            <br></br>
            Thank you!
          </p>
          <Link href={"https://github.com/jorden-io"}>
            <GrGithub
              id="git-btn"
              style={{
                fontSize: "50px",
                marginTop: "25px",
                textDecoration: "none",
                color: "white",
              }}
            />
          </Link>
        </div>
        <span className="line-span"></span>
        <span className="circle-span">
          <p
            style={{
              color: "white",
              fontWeight: "800",
              position: "relative",
              top: "-7px",
            }}
          >
            1
          </p>
        </span>
        <h2 id="algo-vis">algorithm visualizer</h2>
        <div className="grid-container">
          <Grid matrix={new Matrix(20, 40)} />
          <hr
            style={{
              position: "absolute",
              marginTop: "-45px",
              border: "solid 1px rgb(18, 18, 18)",
              width: "95%",
              transition: "1s",
            }}
          ></hr>
          <hr
            className="vert-hr"
            style={{
              position: "absolute",
              marginTop: "-44px",
              border: "none",
              padding: "1px",
              //border: "solid 1px rgb(18, 18, 18)",
              height: "30px",
              transition: "1s",
            }}
          ></hr>
          <p
            className="av-p"
            style={{ position: "absolute", marginTop: "-35px", left: "150px" }}
          >
            speaks for itself, src here:
          </p>
          <Link
            className="av-git-link"
            href={"https://github.com/jorden-io/PathFindVisualizer"}
          >
            <DiGithubFull
              style={{
                position: "absolute",
                marginTop: "-48px",
                fontSize: "50px",
                right: "200px",
                color: "cyan",
              }}
            />
          </Link>
          <button>
            <Link href={""}>{/* <BsFileEarmarkCode /> */}</Link>
          </button>
          <h2>chess</h2>
        </div>
        <div
          className="line-container"
          style={{
            position: "absolute",
            display: "flex",
            justifyContent: "center",
            marginTop: "1020px",
          }}
        >
          <span className="line-span"></span>
          <span className="circle-span">
            <p
              style={{
                color: "white",
                fontWeight: "800",
                position: "relative",
                top: "-7px",
              }}
            >
              2
            </p>
          </span>
        </div>
      </div>
      <div>
        <div id="chess-info" className="chess-info">
          <h1>Check Mate</h1>
          <hr></hr>
          <p>
            Everyone loves chess, thats why I wanted to make my own! Implemented
            from scratch, to every possible move, to the UI design! play with
            friends or just by yourself.
            <br></br>
            src here:
          </p>
          <Link href={"https://github.com/jorden-io/chess"}>
            <DiGithubFull
              style={{
                fontSize: "60px",
                color: "cyan",
                position: "relative",
                zIndex: 9,
              }}
            />
          </Link>
          <img
            style={{
              width: "350px",
              position: "absolute",
              right: "0px",
              top: "0px",
            }}
            src="/king.png"
          ></img>
        </div>
        <br></br>
        <br></br>
        <br></br>
        <div className="board-c-inner">
          <Board matrix={new cMatrix()} />
        </div>
      </div>
      <div className="jr-footer" style={{ position: "relative", top: "500px" }}>
        <hr style={{ border: "solid 1px rgb(18, 18, 18)" }}></hr>
        <img
          style={{
            width: "85px",
            height: "85px",
            padding: "0px",
            marginTop: "-10px",
          }}
          src="/jr.png"
        ></img>
        {/* <p style={{ fontWeight: "200", padding: "25px", marginTop: "-10px" }}>
          thank you!
        </p> */}
        {/* <button></button> */}
      </div>
      {/* <p> hello! </p> */}
    </>
  );
}
